heat_template_version: 2016-04-08
description: Template for setting up an OpenShift Origin environment
parameters:
  dns_prefix:
    description: your DNS prefix
    type: string
    default: imolab.it
  dns_server:
    description: upstream DNS server
    type: string
    default: 192.168.188.3
  key_name:
    description: name of a key pair to enable SSH access to the instances
    type: string
  instance_type:
    description: instance type for server
    type: string
    default: m1.small
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge, m1.pippo]
        description: must be a valid instance type
  user_name:
    description: user name for OpenShift login
    type: string
    default: openshift
  password:
    description: password for OpenShift login
    type: string
    default: password
  network_name: 
    description: specific network selection
    type: string
    default: n1
  image:
    type: string
    description: The image to be used for the server.
    constraints:
      - custom_constraint: glance.image
resources:
  OpenShift:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: instance_type}
      key_name: {get_param: key_name}
      networks:
      - network: {get_param: network_name}
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo 'nameserver 8.8.8.8'>>  /etc/resolv.conf
            echo "LOG enter on template"
            yum -y install https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
            yum -y install http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
            yum -y install augeas
            echo "LOG repo config done"
            augtool setm /files/etc/yum.repos.d/puppetlabs.repo/* exclude '*mcollective*\ activemq'
            augtool set /files/etc/sysconfig/network/HOSTNAME broker.$dns_prefix$

            yum install -y puppet facter tar bind
            mkdir -p /etc/puppet/modules && cd /etc/puppet/modules
            puppet module install openshift/openshift_origin --version 4.1.3

            /usr/sbin/dnssec-keygen -a HMAC-MD5 -b 512 -n USER -r /dev/urandom -K /var/named $dns_prefix$
            export DNS_SEC_KEY="`cat /var/named/K$dns_prefix$.*.key  | awk '{print $8}'`"

            cat << EOF > configure_origin.pp
            class { 'openshift_origin' :
                domain                        => '$dns_prefix$',
                node_unmanaged_users          => ['root'],
                development_mode              => true,
                conf_node_external_eth_dev    => '$ext_network$',
                install_method                => 'yum',
                register_host_with_nameserver => true,
                broker_auth_plugin            => 'htpasswd',
                broker_dns_plugin             => 'avahi',
            }            
            EOF

            puppet apply --verbose configure_origin.pp | tee /var/log/configure_origin.log
            reboot
          params:
            $dns_prefix$: { get_param: dns_prefix }
            $dns_server$: { get_param: dns_server }
            $user_name$: { get_param: user_name }
            $password$: { get_param: password }
            $ext_network$: { get_param: network_name }
      user_data_format: RAW
